### PR TITLE
Updates astral-sh/setup-uv action to v5

### PR DESCRIPTION
**Pull request by colindean**
[Caught by dependabot](https://github.com/colindean/transmission-blocklist/pull/9) moments after I set it up in one of my repos.

### CODE REVIEW

**Review by woodruffw — APPROVED** [review]
Thanks @colindean! FYI we have Dependabot configured here so this will be bumped automatically as well in the future.

**Review by woodruffw — APPROVED** [review]

**Comment by woodruffw** [comment]
CC @ubiratansoares for viz: it looks like the latest version of `setup-uv` switches to "caching enabled by default," so now we need to think about that version handling behavior in the cache poisoning audit 🙂

**Comment by colindean** [comment]
It seemed to me like dependabot may not update the example embedded inside of the documentation. It would be surprising to me if it did do so inside of fenced blocks inside of markdown files, but certainly welcome!

**Comment by woodruffw** [comment]
Oh, my bad -- I misread the source file here. I thought this was being generated from a snippet that Dependabot was tracking, but it's still embedded in the markdown itself!

**Comment by colindean** [comment]
It would be really cool if the docs pulled it in from a live example.

**Pull request merged**
