### PR TITLE
feat: accept multiple arguments as inputs

### PR DESCRIPTION
**Pull request by miketheman**
Accept multiple individual files as inputs.
Useful with other mutli-file processing like xargs or other tools, so as to not have to invoke zizmor multiple times, and distinct from operating on an entire directory.

### CODE REVIEW

**Comment by miketheman** [comment]
Easier to review ignoring whitespace: https://github.com/woodruffw/zizmor/pull/104/files?w=1

**Review by woodruffw — APPROVED** [review]

**Review by woodruffw — APPROVED** [review]
Thanks @miketheman!

**Comment by woodruffw** [comment]
I thought a bit about this, and I think it might make sense to restrict the inputs slightly (but not as much as they were before). 

Concretely, instead of `<dir | file> [dir | file] ...`, I'm thinking `<dir | file [file ...]>` so that there's only ever one directory at most, but the user can still pass in multiple files explicitly if they please.

My rationale for this is that it'll make config (#12) discover a little easier: with just one directory, there's only one place where the config needs to be discovered.

Thoughts @miketheman?

**Comment by woodruffw** [comment]
I thought about this more, and I'm probably overcomplicating it. For now I'll do autodiscovery via `${CWD}` and also support a `--config` flag; the rest can come later if needed.

**Pull request merged**
