### PR TITLE
docs: add template-injection tips

### PR DESCRIPTION
**Pull request by woodruffw**
See convo in https://github.com/python/cpython/pull/127749#discussion_r1875081281.

CC @sethmlarson @alexwaygood @hugovk

### CODE REVIEW

**Comment by woodruffw** [comment]
> What are your thoughts on adding a linkable heading that you can put directly into Zizmor's error's, so users are able to see these tips right after the scanner runs and know what to do to remediate?

It's already there! The finding IDs should be clickable in your terminal, and will take you directly to each audit's docs.

(I'm open to ideas for how to better surface this -- OSC 8 links are great for hyperlinking but they don't make it obvious when a thing is a link 😅)

**Comment by hugovk** [comment]
> It's already there! The finding IDs should be clickable in your terminal, and will take you directly to each audit's docs.

I found this by mistake, it was a nice surprise and subsequently useful :) 🚀

**Review by hugovk — APPROVED** [review]
Thank you!

**Comment by AlexWaygood** [comment]
Thanks! :D

**Pull request merged**
